// Code generated by MockGen. DO NOT EDIT.
// Source: internal/movie/core/movie.go

// Package mock_core is a generated GoMock package.
package mock_core

import (
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockMovie is a mock of Movie interface
type MockMovie struct {
	ctrl     *gomock.Controller
	recorder *MockMovieMockRecorder
}

// MockMovieMockRecorder is the mock recorder for MockMovie
type MockMovieMockRecorder struct {
	mock *MockMovie
}

// NewMockMovie creates a new mock instance
func NewMockMovie(ctrl *gomock.Controller) *MockMovie {
	mock := &MockMovie{ctrl: ctrl}
	mock.recorder = &MockMovieMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockMovie) EXPECT() *MockMovieMockRecorder {
	return m.recorder
}

// SaveLog mocks base method
func (m *MockMovie) SaveLog(title string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveLog", title)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveLog indicates an expected call of SaveLog
func (mr *MockMovieMockRecorder) SaveLog(title interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveLog", reflect.TypeOf((*MockMovie)(nil).SaveLog), title)
}
