// Code generated by protoc-gen-go. DO NOT EDIT.
// source: searchapp.proto

package searchapp

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type MovieRequest struct {
	Title                string   `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Page                 int64    `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MovieRequest) Reset()         { *m = MovieRequest{} }
func (m *MovieRequest) String() string { return proto.CompactTextString(m) }
func (*MovieRequest) ProtoMessage()    {}
func (*MovieRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_searchapp_6b17b472112fd907, []int{0}
}
func (m *MovieRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MovieRequest.Unmarshal(m, b)
}
func (m *MovieRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MovieRequest.Marshal(b, m, deterministic)
}
func (dst *MovieRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MovieRequest.Merge(dst, src)
}
func (m *MovieRequest) XXX_Size() int {
	return xxx_messageInfo_MovieRequest.Size(m)
}
func (m *MovieRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MovieRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MovieRequest proto.InternalMessageInfo

func (m *MovieRequest) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *MovieRequest) GetPage() int64 {
	if m != nil {
		return m.Page
	}
	return 0
}

type MovieResponse struct {
	Search               []*MovieDetail `protobuf:"bytes,1,rep,name=search,proto3" json:"search,omitempty"`
	TotalResults         string         `protobuf:"bytes,2,opt,name=totalResults,proto3" json:"totalResults,omitempty"`
	Response             string         `protobuf:"bytes,3,opt,name=response,proto3" json:"response,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *MovieResponse) Reset()         { *m = MovieResponse{} }
func (m *MovieResponse) String() string { return proto.CompactTextString(m) }
func (*MovieResponse) ProtoMessage()    {}
func (*MovieResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_searchapp_6b17b472112fd907, []int{1}
}
func (m *MovieResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MovieResponse.Unmarshal(m, b)
}
func (m *MovieResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MovieResponse.Marshal(b, m, deterministic)
}
func (dst *MovieResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MovieResponse.Merge(dst, src)
}
func (m *MovieResponse) XXX_Size() int {
	return xxx_messageInfo_MovieResponse.Size(m)
}
func (m *MovieResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MovieResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MovieResponse proto.InternalMessageInfo

func (m *MovieResponse) GetSearch() []*MovieDetail {
	if m != nil {
		return m.Search
	}
	return nil
}

func (m *MovieResponse) GetTotalResults() string {
	if m != nil {
		return m.TotalResults
	}
	return ""
}

func (m *MovieResponse) GetResponse() string {
	if m != nil {
		return m.Response
	}
	return ""
}

type MovieDetail struct {
	Title                string   `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Year                 string   `protobuf:"bytes,2,opt,name=year,proto3" json:"year,omitempty"`
	ImdbID               string   `protobuf:"bytes,3,opt,name=imdbID,proto3" json:"imdbID,omitempty"`
	Type                 string   `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	Poster               string   `protobuf:"bytes,5,opt,name=poster,proto3" json:"poster,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MovieDetail) Reset()         { *m = MovieDetail{} }
func (m *MovieDetail) String() string { return proto.CompactTextString(m) }
func (*MovieDetail) ProtoMessage()    {}
func (*MovieDetail) Descriptor() ([]byte, []int) {
	return fileDescriptor_searchapp_6b17b472112fd907, []int{2}
}
func (m *MovieDetail) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MovieDetail.Unmarshal(m, b)
}
func (m *MovieDetail) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MovieDetail.Marshal(b, m, deterministic)
}
func (dst *MovieDetail) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MovieDetail.Merge(dst, src)
}
func (m *MovieDetail) XXX_Size() int {
	return xxx_messageInfo_MovieDetail.Size(m)
}
func (m *MovieDetail) XXX_DiscardUnknown() {
	xxx_messageInfo_MovieDetail.DiscardUnknown(m)
}

var xxx_messageInfo_MovieDetail proto.InternalMessageInfo

func (m *MovieDetail) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *MovieDetail) GetYear() string {
	if m != nil {
		return m.Year
	}
	return ""
}

func (m *MovieDetail) GetImdbID() string {
	if m != nil {
		return m.ImdbID
	}
	return ""
}

func (m *MovieDetail) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *MovieDetail) GetPoster() string {
	if m != nil {
		return m.Poster
	}
	return ""
}

func init() {
	proto.RegisterType((*MovieRequest)(nil), "searchapp.MovieRequest")
	proto.RegisterType((*MovieResponse)(nil), "searchapp.MovieResponse")
	proto.RegisterType((*MovieDetail)(nil), "searchapp.MovieDetail")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// SearchAppClient is the client API for SearchApp service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SearchAppClient interface {
	GetMovieByTitle(ctx context.Context, in *MovieRequest, opts ...grpc.CallOption) (*MovieResponse, error)
}

type searchAppClient struct {
	cc *grpc.ClientConn
}

func NewSearchAppClient(cc *grpc.ClientConn) SearchAppClient {
	return &searchAppClient{cc}
}

func (c *searchAppClient) GetMovieByTitle(ctx context.Context, in *MovieRequest, opts ...grpc.CallOption) (*MovieResponse, error) {
	out := new(MovieResponse)
	err := c.cc.Invoke(ctx, "/searchapp.SearchApp/GetMovieByTitle", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SearchAppServer is the server API for SearchApp service.
type SearchAppServer interface {
	GetMovieByTitle(context.Context, *MovieRequest) (*MovieResponse, error)
}

func RegisterSearchAppServer(s *grpc.Server, srv SearchAppServer) {
	s.RegisterService(&_SearchApp_serviceDesc, srv)
}

func _SearchApp_GetMovieByTitle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MovieRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchAppServer).GetMovieByTitle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/searchapp.SearchApp/GetMovieByTitle",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearchAppServer).GetMovieByTitle(ctx, req.(*MovieRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _SearchApp_serviceDesc = grpc.ServiceDesc{
	ServiceName: "searchapp.SearchApp",
	HandlerType: (*SearchAppServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetMovieByTitle",
			Handler:    _SearchApp_GetMovieByTitle_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "searchapp.proto",
}

func init() { proto.RegisterFile("searchapp.proto", fileDescriptor_searchapp_6b17b472112fd907) }

var fileDescriptor_searchapp_6b17b472112fd907 = []byte{
	// 261 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x91, 0x4f, 0x4b, 0xc3, 0x40,
	0x10, 0xc5, 0x8d, 0x6d, 0x83, 0x99, 0x56, 0x0a, 0x8b, 0xd4, 0xa5, 0xa7, 0x90, 0x53, 0x4e, 0x39,
	0xd4, 0x8b, 0x57, 0xa5, 0x28, 0x1e, 0xbc, 0x6c, 0xfd, 0x02, 0x5b, 0x1d, 0x34, 0x10, 0xdd, 0x71,
	0x77, 0x2a, 0x04, 0x0f, 0x7e, 0x75, 0xc9, 0xec, 0x52, 0xff, 0xe1, 0x6d, 0xde, 0xcc, 0xcb, 0x6f,
	0xe6, 0x65, 0x61, 0x1e, 0xd0, 0xfa, 0xfb, 0x27, 0x4b, 0xd4, 0x90, 0x77, 0xec, 0x54, 0xb1, 0x6f,
	0x54, 0xe7, 0x30, 0xbb, 0x75, 0x6f, 0x2d, 0x1a, 0x7c, 0xdd, 0x61, 0x60, 0x75, 0x02, 0x13, 0x6e,
	0xb9, 0x43, 0x9d, 0x95, 0x59, 0x5d, 0x98, 0x28, 0x94, 0x82, 0x31, 0xd9, 0x47, 0xd4, 0x87, 0x65,
	0x56, 0x8f, 0x8c, 0xd4, 0xd5, 0x07, 0x1c, 0xa7, 0x2f, 0x03, 0xb9, 0x97, 0x80, 0xaa, 0x81, 0x3c,
	0x72, 0x75, 0x56, 0x8e, 0xea, 0xe9, 0x6a, 0xd1, 0x7c, 0xed, 0x15, 0xe7, 0x1a, 0xd9, 0xb6, 0x9d,
	0x49, 0x2e, 0x55, 0xc1, 0x8c, 0x1d, 0xdb, 0xce, 0x60, 0xd8, 0x75, 0x1c, 0x04, 0x5e, 0x98, 0x1f,
	0x3d, 0xb5, 0x84, 0x23, 0x9f, 0xf8, 0x7a, 0x24, 0xf3, 0xbd, 0xae, 0xde, 0x61, 0xfa, 0x0d, 0xfb,
	0xff, 0xe5, 0x3d, 0x5a, 0x9f, 0xe0, 0x52, 0xab, 0x05, 0xe4, 0xed, 0xf3, 0xc3, 0xf6, 0x66, 0x9d,
	0x90, 0x49, 0x0d, 0x5e, 0xee, 0x09, 0xf5, 0x38, 0x7a, 0x87, 0x7a, 0xf0, 0x92, 0x0b, 0x8c, 0x5e,
	0x4f, 0xa2, 0x37, 0xaa, 0xd5, 0x06, 0x8a, 0x8d, 0xc4, 0xb8, 0x20, 0x52, 0x57, 0x30, 0xbf, 0x46,
	0x96, 0x63, 0x2e, 0xfb, 0x3b, 0xd9, 0x7b, 0xfa, 0x3b, 0x7c, 0xfa, 0xc1, 0x4b, 0xfd, 0x77, 0x90,
	0xf2, 0x1c, 0x6c, 0x73, 0x79, 0x9e, 0xb3, 0xcf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x7c, 0xdd, 0x5a,
	0x6b, 0xb1, 0x01, 0x00, 0x00,
}
